import type { Metadata } from "next";
import { Sora, Russo_One, Luckiest_Guy } from "next/font/google";
import "./globals.css";
import HeaderSection from "@/layout/header/Header";

const sora = Sora({
    variable: "--font-sora",
    subsets: ["latin"],
});

const russoOne = Russo_One({
    weight: "400",
    variable: "--font-russo-one",
    subsets: ["latin"],
});

const luckiestGuy = Luckiest_Guy({
    weight: "400",
    variable: "--font-luckiest-guy",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Palak - Personal Portfolio || Next.js",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${sora.variable} ${russoOne.variable} ${luckiestGuy.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <HeaderSection />
                <main>{children}</main>
            </body>
        </html>
    );
}
