import "./globals.css";
import type { Metadata } from "next";
import { Sora, Russo_One, Luckiest_Guy } from "next/font/google";
import HeaderSection from "@/layout/header/Header";
import FooterSection from "@/layout/footer/Footer";
import LenisProvider from "@/components/shared/lenis-provider/LenisProvider";
import Breadcrumb from "@/components/shared/breadcrumb/Breadcrumb";

const sora = Sora({
    variable: "--font-sora",
    subsets: ["latin"],
});

const russoOne = Russo_One({
    weight: "400",
    variable: "--font-russo-one",
    subsets: ["latin"],
});

const luckiestGuy = Luckiest_Guy({
    weight: "400",
    variable: "--font-luckiest-guy",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Polok's - Portfolio Website",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${sora.variable} ${russoOne.variable} ${luckiestGuy.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <LenisProvider>
                    <HeaderSection />
                    <main>
                        <Breadcrumb />
                        {children}
                    </main>
                    <FooterSection />
                </LenisProvider>
            </body>
        </html>
    );
}
